Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/__init__.py", line 1133, in _main
    main()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/__init__.py", line 905, in main
    operation_func(esp, args)
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/cmds.py", line 598, in write_flash
    esp.flash_defl_block(block, seq, timeout=timeout)
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/loader.py", line 131, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/loader.py", line 1066, in flash_defl_block
    self.check_command(
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/loader.py", line 465, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/esptool/loader.py", line 452, in command
    self._port.timeout = saved_timeout
    ^^^^^^^^^^^^^^^^^^
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/serial/serialutil.py", line 372, in timeout
    self._reconfigure_port()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.11_env/lib/python3.11/site-packages/serial/serialposix.py", line 517, in _reconfigure_port
    termios.tcsetattr(
termios.error: (6, 'Device not configured')
CMake Error at run_serial_tool.cmake:66 (message):
  
  /Users/fox/.espressif/python_env/idf5.1_py3.11_env/bin/python;;/Users/fox/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



