Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 712, in main
    esp = esp or get_default_connected_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1024, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/loader.py", line 678, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/loader.py", line 578, in _connect_attempt
    self.flush_input()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/esptool/loader.py", line 492, in flush_input
    self._port.flushInput()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/serial/serialutil.py", line 588, in flushInput
    self.reset_input_buffer()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 683, in reset_input_buffer
    self._reset_input_buffer()
  File "/Users/fox/.espressif/python_env/idf5.1_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 677, in _reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (6, 'Device not configured')
CMake Error at run_serial_tool.cmake:66 (message):
  
  /Users/fox/.espressif/python_env/idf5.1_py3.12_env/bin/python;;/Users/fox/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



